[build]
command = "npm run build"
dist = "dist"

[site]
bucket = "./dist"

[site.headers]
"/*.js" = { Content-Type = "application/javascript; charset=utf-8" }
"/*.jsx" = { Content-Type = "application/javascript; charset=utf-8" }
"/*.css" = { Content-Type = "text/css; charset=utf-8" }
"/*" = { X-Frame-Options = "DENY", X-Content-Type-Options = "nosniff" } 